name: Build and release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.1
      with:
        dotnet-version: 6.0.x

    - name: Verify .NET
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --no-restore
        dotnet publish -r linux-x64 -p:PublishSingleFile=true -c Release --self-contained true --nologo
        dotnet publish -r osx-x64 -p:PublishSingleFile=true -c Release --self-contained true --nologo
        dotnet publish -r win-x64 -p:PublishSingleFile=true -c Release --self-contained true --nologo

    - name: Upload Linux Build
      uses: actions/upload-artifact@v3
      with:
        name: nng-one-linux64
        path: /home/runner/work/nng-one/nng-one/bin/Release/net6.0/linux-x64/publish/

    - name: Upload macOS Build
      uses: actions/upload-artifact@v3
      with:
        name: nng-one-osx
        path: /home/runner/work/nng-one/nng-one/bin/Release/net6.0/osx-x64/publish/

    - name: Upload Windows Build
      uses: actions/upload-artifact@v3
      with:
        name: nng-one-win64
        path: /home/runner/work/nng-one/nng-one/bin/Release/net6.0/win-x64/publish/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Download Linux build
      uses: actions/download-artifact@v3
      with:
        name: nng-one-linux64
        path: linux64

    - name: Download macOS build
      uses: actions/download-artifact@v3
      with:
        name: nng-one-osx
        path: osx

    - name: Download Windows build
      uses: actions/download-artifact@v3
      with:
        name: nng-one-win64
        path: win64

    - name: Zip all builds
      run: |
        zip nng-one-linux64.zip linux64/*
        zip nng-one-osx.zip osx/*
        zip nng-one-win64.zip win64/*

    - name: Create GitHub release
      id: github_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "1.4.0"
        release_name: "1.4.0"

    - name: Upload Linux build to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: /home/runner/work/nng-one/nng-one/nng-one-linux64.zip
        asset_name: nng-one-linux64.zip
        asset_content_type: application/zip

    - name: Upload macOS build to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: /home/runner/work/nng-one/nng-one/nng-one-osx.zip
        asset_name: nng-one-osx.zip
        asset_content_type: application/zip

    - name: Upload Windows build to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: /home/runner/work/nng-one/nng-one/nng-one-win64.zip
        asset_name: nng-one-win64.zip
        asset_content_type: application/zip
